### ISSUE TITLE
Profile > Log Out: Causing 404 page not found

### ISSUE THREAD

**Issue by joonhoswe** [AustinWheel/angel-trading-co#11]
Not sure why this is happening as it wasn't happening in testing.

https://github.com/AustinWheel/angel-trading-co/assets/149014867/e786b63f-17a0-4476-84db-ad837cf3c082

**Comment by AustinWheel** [comment]
Should be fixed now, will keep monitoring the Netlify 404 error page bc if its a DNS issue then it might resolve in 24-48 hours
